// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://parbjhdbzotkhtisapzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcmJqaGRiem90a2h0aXNhcHp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDcxMzUsImV4cCI6MjA1ODgyMzEzNX0.TOxMqKeHQxPZH8CsBLjbjYM4kc96uFpCuEOdOHOysVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);